### PR TITLE
Bug fixes

### LINKED ISSUE #255: Some charts on category pages are not flipped to rtl
Second set of charts are not flipped: 
screen shot 2017-02-06 at 11 40 27 am

### PR DESCRIPTION
**Pull request by nbumbarger**
Also closes #255

### CODE REVIEW

File: app/assets/scripts/views/project.js [hunk 1]
```diff
@@ -62,6 +62,7 @@ var Project = React.createClass({
   },
 
   render: function () {
+    // console.log(this.props)
```
Comment (dereklieu) [inline app/assets/scripts/views/project.js]: This should be removed.

File: app/assets/scripts/views/project.js [hunk 2]
```diff
@@ -143,7 +149,7 @@ var Project = React.createClass({
                 </ul>
               </div>
               <dl className={'inpage-meta project--' + ontime}>
-                <dt className='inpage-meta__label visually-hidden'>Status</dt>
+                <dt className='inpage-meta__label'>Status <span className='inpage-meta__label--light'>{data.status[lang]}</span></dt>
```
Comment (dereklieu) [inline app/assets/scripts/views/project.js]: This should be in the translation yml files rather than hard-coded, and the english version should have a colon after "Status".
