### PR TITLE
fixed weird spacing when too many stats are showing

### LINKED ISSUE #292: Display of projects with Funding, Loans, Households, and Grants
This project includes all 4 attributes when logged in, which don't appear to display properly
https://map-egypt.github.io/#/en/projects/8ab3f420-c74a-422a-9ff3-03be6918d367

### PR DESCRIPTION
**Pull request by felskia**
Closes #292

### CODE REVIEW

File: app/assets/scripts/views/project.js [hunk 1]
```diff
@@ -223,14 +223,12 @@ var Project = React.createClass({
                   <li>{tally(data.number_served.number_served)} <small>{data.number_served.number_served_unit}</small></li>
                 </ul>
                 {disbursedFunds.loan || disbursedFunds.grant
-                  ? <ul className='inpage-stats'>
```
Comment (nbumbarger) [inline app/assets/scripts/views/project.js]: @felskia the `?` here indicates that this is part of a logic block. It makes it so that that the `ul` will not be written at all when neither loans or grants are available for a project. Essentially, it says "if there are loans or grants, write a `ul`", and then "if there is a loan, write an `li` inside of it, and if there is a grant, write an `li` inside of it." Removing the top of the logic block causes a Javascript error and prevents the site from being built, and the `ul` also needs to be there structurally in order to hold the `li`s when they exist.

**Comment by felskia** [comment]
@DylanMoriarty do you think you'd have a second to fix this little thing?

**Comment by DylanMoriarty** [comment]
Should be fixed @felskia @nbumbarger .
